version: '3'
services:
    nginx:
        container_name: ACADEMIA_NGNIX
        image: 'nginx:latest'
        ports:
            - '80:8080'
        volumes:
            - './var/www:/var/www'
            - './config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
            - './config/nginx/conf.d/:/etc/nginx/conf.d/:ro'
        networks:
            - lempnet
    php:
        container_name: ACADEMIA_PHP_FPM
        build: ./config/php-fpm
        ports:
            - '9000'
        env_file:
            - ./config.env
        volumes:
            - './var/www:/var/www'
            - './config/php-fpm/php.ini:/usr/local/etc/php/php.ini:ro'
        networks:
            - lempnet
    mysqldb:
        container_name: ACADEMIA_MYSQL
        image: 'mysql:5.7'
        volumes:
            - './data/mysql:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD=root123!
            - MYSQL_USER=myuser
            - MYSQL_PASSWORD=mypassword
            - MYSQL_DATABASE=academia
        ports:
            - '3306:3306'
        networks:
            - lempnet
    phpmyadmin:
        container_name: ACADEMIA_PHPMYADMIN
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        environment:
            - MYSQL_ROOT_PASSWORD=rootpass
            - PMA_HOST=mysqldb
        depends_on:
            - mysqldb
        networks:
            - lempnet
networks:
    lempnet:
        driver: bridge
